apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: expense-tracker
data:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres_password@postgres-service:5432/expense_tracker"
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"