apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: expense-tracker
type: Opaque
data:
  # echo -n 'your-jwt-secret-key-change-in-production' | base64
  JWT_SECRET_KEY: eW91ci1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==