apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: expense-tracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # For Raspberry Pi, you might want to specify a storage class
  # storageClassName: local-path  # or whatever your K3s uses