apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: expense-tracker
type: Opaque
data:
  # echo -n 'your-password' | base64
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=  # postgres_password
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_DB: ZXhwZW5zZV90cmFja2Vy  # expense_tracker